### ISSUE TITLE
Missing feature in TegraScript or I'm blind

### ISSUE THREAD

**Issue by JrRadiant** [suchmememanyskill/TegraScript#12]
Hi, thanks for such a great utility and script solution system! It's nice.

I've wonder, how to rename a folder (in my example, it's /atmosphere/contents/0100000000001000) into the _100000000001000 via the TegraScript?

I tried to look into the readme but just cannot find these functions.
Please help the newbie here. :)

Thanks!

**Comment by suchmememanyskill** [comment]
Filemove works for it, maybe i should've specified that in the readme

**Comment by JrRadiant** [comment]
@suchmememanyskill 
Wow, nice!

Excuse me, but would you be so kind to give me an example to use fileMove(string src, string dst) to rename the folder?

Thank you in advance!

**Comment by suchmememanyskill** [comment]
`fileMove("sd:/randomFolder", "sd:/newRandomFolder")`

**Comment by JrRadiant** [comment]
Awesome, got it, thank you very much!
