### ISSUE TITLE
systemwipe.te error

### ISSUE THREAD

**Issue by TheOneEyedGrimReaper** [suchmememanyskill/TegraScript#17]
i have a bricked switch and wanted to resurrect it with pikafix but the systemwipe.te script just throws this in my fcking face.
[FATAL] Variable /printf/ not found
Error occured on or near line 1

**Comment by suchmememanyskill** [comment]
This sounds like you're using an outdated version of the systemwipe script. Are you using the one from this repository?

**Comment by TheOneEyedGrimReaper** [comment]
> This sounds like you're using an outdated version of the systemwipe script. Are you using the one from this repository?

Yeah i'm using the latest.
But i figured out what was the real problem.
For the bricked switch i don't have the original emmc or the backup.
I restored a backup from my working switch.
With the pikafix the system and the others accept the non working switch biskeys.
But the user partition is just accepts the good switch biskeys.
Now i'm created a user.bin file with the faulty switch biskeys with the nxnandmanager, and i'm going to restore it and try it out later.
But first i need to restore my working switch nand backup again and start over all of the things because something went wrong with the systemrestore.te and my touch panel is not working right now.
