### ISSUE TITLE
Extracting sysMMC USER saves without (Windows) PC?

### ISSUE THREAD

**Issue by ghost** [suchmememanyskill/TegraScript#18]
Hello! Apologies for not using Discord to contact you as I'm not able to use it,

I have a hacked console that's having SD issues (replaced the reader, it didn't work), so I'm preparing to sell it, and buy a new hackable Switch.

I used the Tegra script `Dump_saves.te`, and it worked fine. I think all my saves from the USER partition are backed up fine. Of course, they're still encrypted.

So whenever I try to boot CFW Horizon, I get an error, so I can't use a HOS-based homebrew to back my save files up. Which is why I'm resorting to your method (and thank you for your hard work!!!)

I also don't have access to a Windows PC, or really a PC at all. I can only run Switchroot Ubuntu on my Switch as a PC lol!

I assume that the way I'm to decrypt my save is in the method outlined in [your guide](https://suchmememanyskill.github.io/guides/switchextractsaves/#step-2-extracting-the-saves) to extract saves, correct?

Problem is, like I said, I don't have a Windows PC to extract them with.

If it's not too much to ask, could you possibly assist me in extracting them somehow?

I trust you because you're a noted homebrew developer and a community member, so I'll be more than willing to provide my saves and prod.keys file.

Thank you very much and I'm very sorry for the bother!! If you're unable to help me, no worries, I'll somehow figure it out...

**Comment by suchmememanyskill** [comment]
I do hope you realise this is a public issue. Anyone can see this post. I'd rather you didn't just put a prod.keys on my repo

What's the error you get while booting cfw?

**Comment by suchmememanyskill** [comment]
https://drive.google.com/file/d/1UmoHWNISVwpCdJgIeMMiNWZhgIoSjHFK/view?usp=sharing enjoy i suppose

**Comment by ghost** [comment]
> https://drive.google.com/file/d/1UmoHWNISVwpCdJgIeMMiNWZhgIoSjHFK/view?usp=sharing enjoy i suppose

You're a lifesaver. I apologize for the ruckus I caused, and I deleted the Drive link. I appreciate this so much.
