### ISSUE TITLE
fwdump.te for cnmt.nca

### ISSUE THREAD

**Issue by deejay87** [suchmememanyskill/TegraScript#3]
Hi
Possible to update the dump firmware for the new files cnmt.nca ?
Thanks

**Comment by suchmememanyskill** [comment]
hi
Currently checking if files are meta/content nca's is not possible in tegrascript. I may add this later, in the rewrite

**Comment by suchmememanyskill** [comment]
fwdump.te now dumps files with .cnmt.nca extentions
