### ISSUE TITLE
script example delete files

### ISSUE THREAD

**Issue by lowburger** [suchmememanyskill/TegraScript#7]
Hi. I want to learn simple script for deleting sd card files but I'm not programmer so it's difficult. Could you make example script maybe?

I wish to delete custom theme for example, it's a good one because it can stop boot. The locations:
atmosphere/contents/0100000000001000
atmosphere/contents/0100000000001013
atmosphere/exefs_patches/NxThemesInstaller

I know I can find with browser but script is very fast :) Thanks

**Comment by suchmememanyskill** [comment]
dirDel(path)?

So in your case that'd be

```
dirDel("atmosphere/contents/01000000001000")
dirDel("atmosphere/contents/01000000001013")
dirDel("atmosphere/exefs_patches/NxThemesInstaller")
```

**Comment by lowburger** [comment]
Thx I didn't know is so simple, I'm thinking more code is needed for menu and so on! :)
I write wrong id on first post but fixed.

**Comment by suchmememanyskill** [comment]
Actually, i forgot something. It may still pick the sd, but just to make sure put `sd:` in front of the path, so `dirDel("sd:/atmosphere/contents/01000000001000")`

**Comment by lowburger** [comment]
Yes it picked sd but I will add it thx. You can say how to add simple menu, delete or exit?

**Comment by suchmememanyskill** [comment]
```
res = menu(["Exit", "Delete QLaunch Mods"], 0)
if (res == 1){
    # Do deletion stuffs
    println("Done!")
}
```

**Comment by lowburger** [comment]
Thx I made it and it works, it looks ok or you recommend a change?
```
ver = version()
println("Delete Custom Theme")
println("Running on TE ", ver)
println()

res = menu(["Exit", "Delete Custom Theme"], 0)

if (res == 0){
	exit()
}

if (res == 1){
	color("RED")
	println("Deleting Custom Theme")
	dirDel("sd:/atmosphere/contents/0100000000001000")
	dirDel("sd:/atmosphere/contents/0100000000001013")
	dirDel("sd:/atmosphere/exefs_patches/NxThemesInstaller")
}

clearscreen()

color("GREEN")
print("Deleted custom theme! Press any key to exit")

pause()
exit()
```

**Comment by suchmememanyskill** [comment]
Looks fine. Res == 1 isn't needed as the only possible options are 0 and 1, and you already check for 0

**Comment by lowburger** [comment]
Thanks for all your advices. I don't know if that's good for your repo but you can add if so :) For me it's great thx.
