### ISSUE TITLE
scripts update

### ISSUE THREAD

**Issue by lowburger** [suchmememanyskill/TegraScript#8]
Hi, I want to ask you can update the script "savedumper.te" for new version? It's last important one for new version I think. I thought maybe you forgot this one but sorry if only you are busy :)

**Comment by suchmememanyskill** [comment]
i just noticed there's an issue here, sorry. I don't think it's worth writing a script for copying User:/saves to the sd, the user can do this in the file manager itself. I'll probably remake this once i actually am able to extract saves on console

**Comment by suchmememanyskill** [comment]
I've re-added the script
